version: '3'

volumes:
  static-files:
  songs-cache:
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=raveberry
      - POSTGRES_USER=raveberry
      - POSTGRES_PASSWORD=raveberry
  redis:
    image: redis
  mopidy:
    image: wernight/mopidy
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - songs-cache:/Music/raveberry
      - "/run/user/${UID:-1000}/pulse:/run/user/105/pulse"
  daphne:
    image: raveberry/raveberry
    environment:
      ADMIN_PASSWORD: "admin"
      MOD_PASSWORD: "mod"
      PAD_PASSWORD: "pad"
    command: bash -c "DJANGO_MOCK=1 python manage.py migrate --noinput && scripts/create_users.sh && /usr/local/bin/daphne --bind 0.0.0.0 --port 9000 main.asgi:application"
    expose:
      - 9000
    volumes:
      - static-files:/opt/raveberry/static
      - songs-cache:/Music/raveberry
    depends_on:
      - db
      - redis
      - mopidy
  nginx:
    image: raveberry/raveberry-nginx
    ports:
      - "80:80"
    volumes:
      - static-files:/usr/share/nginx/static
    depends_on:
      - daphne
